## 1.Data Preprocessing

In [27]:
import pandas as pd
pd.set_option('display.max_colwidth', None)

In [28]:
df = pd.read_csv("dataset.csv")
df.shape

(2747, 3)

In [29]:
sample = df.sample(n=1200, random_state=42)

sample.to_csv("sample1200_before_washing.csv", index=False)

In [30]:
dw1 = pd.read_csv("sample1200_before_washing.csv")
dw1.head().style.set_properties(**{
    'text-align': 'left',
    'white-space': 'pre-wrap'
}).set_table_styles(
    [dict(selector='th', props=[('text-align', 'left')])]
)

In [31]:
annotation1 = dw1
annotation1.head()

,id,context,teacher_response
0,train_2679,"Wether Almost. Whether WH - like when, where, what etc. Aha Ok, cool, you sound more confident with this material today, right? Yes Cool. I've got something for today, some bits of it will probably be very familiar, but some maybe new My birthday is __ March. We talked __ Skype. She's always ___ her phone. Could you insert some prepositions please? On march on Skype on her phone 43892.0 in March",Which month is your birthday?
1,train_2714,"So the 'as a result' directly follows the fact that they can't tell it isn't real do you see? yes.. I see it OK cool ... it become more logic, 1. topic sentence 2.the explain of main idea 3.consequence",Yes i think so
2,train_2262,People are very ______ about it ' = same idea - choose an adjective there is a lot of information about the next World CUp Choose a noun from the ones we've just looked at! ok...sorry People are looking forward to it = there is a lot of _________ ? excitement ok good! Coronavirus has caused a lot of _______ among the population. ? fear,yes!
3,train_2520,"At 6 And why are you only going to be studying for 11 years? It's our old programme and all children who went to school 2 years ago study for 12 years I see! It's a new rule then! Very interesting I went to school at 7 I see, me too! I think 7 is a good age to start school. Because you get 7 years of freeeedom :) Not really","and, of course, because children are much more mature at 7"
4,train_1562,"I see :) The first food that came ___ my mind in to! it's a good expression though Are you still in Kovel? Is it still sunny and summery? it is sunny, but a bit coldy Oh that's a shame Ok <STUDENT>, quick memory test. Could you give me an adjective with the opposite meaning? possible - ? impossible yes! logical illogical legal illegal polite impolite expensive inexpensive yes, correct! regular irregular mature immature",correct - ?

In [32]:
annotation1 = annotation1[annotation1['teacher_response'].str.split().str.len() >= 5]
annotation1.sample(5)

,id,context,teacher_response
1154,train_0907,"quarantine Yes, correct spelling, thank you! When everything was stopped in the UK, it was called a lockdown only essential shopping, no going out etc. Great, and one last word from the previous class. Control over our actions that we use to keep doing something hard willpower? yes, well done! Do you think willpower is important? of course it is",Do you think you have a lot of it?
158,train_1273,"toff?? It means posh...so he went to Eton and has a posh accent/way of acting you see? yes, I just checked! toff' is a bit negative - i just used it to share the word! It is common though ok BUT he does have the ability to connect with all kinds of people actually - a very skilled politician right-wing that's why he's divisive",but he's got the gift of the gab
762,train_0279,"what is the 'in law'? My husband's parents are my parents-in-law awww And my parents are his parents-in-law yes, a mother-in-law and a father-in-law I also have a brother-in-law, my husband's brother So my sister is my husband's ??? sister-in-law correct!",it's much simpler in English than in Ukrainian or Russian :)
436,train_0359,"Do you know what I mean? yes good Next one! A stick that wizards can use to do magic is called... magic wand correct! If a wizard cooks some mixture that has magical powers, this mixture is called... ? a potion oops sorry Professor Snape was teaching Potions as you remember no worries, I know this programme does this if the Internet blips yes","Ok, what do we call a big pot for making potions?"
559,train_2209,"yes, rural area OK great phrase yes! So, what's the opposite of 'rural'?! It begins with 'u'! urb...? unban urba..???? urban unban areas yes that's it..and you can add you 'areas' idea = perfect so 'urban areas' = good ok what about 'solve' - can you change that? cause = reason. action = approach solve = address",OK good ideas yes thanks!

In [33]:
annotation1.shape

(746, 3)

In [34]:
annotation1 = annotation1[~annotation1['teacher_response'].str.contains(
    'choose|select|fill in|complete the sentence|look at|choose|fill in | complete | insert |next one| exercise | quick memory test',
    case=False,
    na=False
)]
annotation1 = annotation1[~annotation1['teacher_response'].str.contains('A\)|B\)|C\)|D\)', regex=True)]

In [35]:
annotation1 = annotation1[annotation1['context'].str.split().str.len() >= 20]
annotation1 = annotation1 = annotation1[annotation1['context'].str.split().str.len() < 80]
annotation1.shape

(679, 3)

In [36]:
annotation1.sample(10)

,id,context,teacher_response
1001,train_2627,"so a verb for each one if you can (different verb ) use out supply demand OK nearly! 'Use UP' = good! for the second one rely on And the first one = 'running out/disappearing OK? yes,ok",so the verbs 'supply' and 'demand' are nice verbs in many situations but the problem here is that you have 'very quickly' you see?
98,train_1335,"Yes, all good You must have enjoyed Vinnytsa because it's quieter than Kyiv You might have been a bit bored because there might have been fewer things to do than at home You can't have missed the famous Vinnytsa fountains Things like this okay do you want me to tell you a funny story? Please! do you know smeshariki? The cartoon? yes I do so yesterday I was on a beach Ok and my face was very red yesterday",Did you catch the sun?
545,train_1399,"poor pig and you:( Thank you! It was a very stressful day for us all! <STUDENT>, do you like Harry Potter books? YES , I LOVE THEM Me too! Love them! I am a fan:) I just thought, your usernames remind me of Dumbledore's passwords to his office :) haha, but it is not) Lemon drop, sherbet lemon lemon wedges","I know that they are not the same, but they tend to be names of sweet foods :)"
443,train_0097,plural Sorry you mean you didn't know the word policy was a noun? ways Yes good! yes.. but I studied just now is political. Yes sorry <STUDENT> just to be clear - you know the word policy means 'plan' right? But a specific plan (that a government of company/organisation has) yes..many way to solve problems ways,Yes good! So actually a useful word for IELTS
625,train_0597,"who I met in my class yes good! thanks OK <STUDENT> last example for the past simple...where is he verb in the following?? for example, the National Gallery where with many painting that I could not understand the meaning Sorry hold on..just this bit: or example, the National Gallery where with many painting Do you need a verb here somewhere?? the National Gallery where have many painting.right?",OK thanks hold on - this is a useful question
377,train_0227,"I'm well, yes still at home How are you? Yeah me too - well not great really ...ironically I would be indoors anyway cos of my dodgy leg...but today I am going a bit potty to be honest .....can't wait to get better! ohh sorry to hear that what does potty mean?? It means....doolally! bonkers? mad! Ha mad, I know mad!!",Lots of synonyms! The same in Spanish I guess!
383,train_2060,"Hi <STUDENT> - are you there?! Hi <TEACHER> Hi, how are you doing? How do you say 'passing the days'?? Do you have an expression for that? Um...not really I guess the translation could be ...e.g. 'surviving' or 'getting by' Exactly that... surviving How about you?",Well...surviving I guess! I'm at home now and basically 'social distancing' is the new norm
873,train_2036,"Can you guess what it is? *one of the most important thingS like dress up? Yes, that's right, a verb + preposition that work together and mean something different from just the verb okay Ok, all today's phrasal verbs have something to do with mobile phones! I bet you know a lot of them, let's see","We press the power button, to ___ the phone on / off"
536,train_1678,"well... it is not easy to say no, sure :) A quick quiz, <STUDENT>! could you fill in the gaps with 'meet; and 'see' okay 1. Nice to ___ you (first time you've talked to a person) 2. It was good to ____ you (to a friend) 3. ____ you tomorrow!",4. _____ me at the station at 4
1071,train_1360,received I see but I think it's a very hard to see difference... yes ...that's the trouble with collocations! yesss that's the real difference: use more than meaning and in which situations would you use 'hit with'? you wouldn't! i.e. just hit + object ahhhh,it seems like it should have a preposition I know but no...!

In [37]:
mask_q = annotation1['context'].str.contains(r'\?', na=False)
mask_uncert =annotation1['context'].str.contains(
    r'not sure|maybe|i think|i guess|probably|seems|could it|is it|does it mean|am i right|right\?',
    case=False, regex=True, na=False
)
mask_teacher_support = annotation1['teacher_response'].str.contains(
    r'good question|well done|great|nice|no worries|don\'t worry|that\'s ok|exactly|you\'re right|almost|close|let\'s|we can|try|step by step|ok|why not|yes|!',
    case=False, regex=True, na=False
)
print(mask_q.sum(), mask_uncert.sum(), mask_teacher_support.sum())

561 292 396

In [38]:
mask_keep = mask_q & mask_uncert | mask_teacher_support
filtered = annotation1[mask_keep]

print(filtered.shape)

(503, 3)

In [39]:
import re

text = filtered['context'].fillna("").str.lower()

# 1) frustration（情绪挫败）
pat_fru = r"\b(" \
    r"frustrat\w*|annoy\w*|irritat\w*|upset\w*|" \
    r"angr\w*|furi\w*|exasperat\w*|agitat\w*|" \
    r"stress\w*|overwhelm\w*|exhaust\w*|tire\w*|" \
    r"fed-up|discourag\w*|dishearten\w*|demotivat\w*|" \
    r"hopeless\w*|helpless\w*|defeat\w*|desperat\w*|" \
    r"resentful\w*|impatient\w*|bitter\w*|tense\w*|" \
    r"unhappy\w*|dissatisf\w*|miserabl\w*|bother\w*" \
r")\b"

# 2) difficulty（任务难、卡住、做不出）
pat_diff = r"\b(" \
    r"difficult\w*|hard\w*|challeng\w*|complex\w*|" \
    r"complicat\w*|tough\w*|trick\w*|demand\w*|" \
    r"burdensom\w*|tax\w*|struggl\w*|fail\w*|" \
    r"stumbl\w*|falter\w*|block\w*|hinder\w*|" \
    r"obstruct\w*|hamper\w*|imped\w*|slow\w*|" \
    r"delay\w*|strain\w*|pressur\w*|overload\w*" \
r")\b"

# 3) confusion（不理解/不确定/求确认）
pat_conf = r"\b(" \
    r"confus\w*|uncertain\w*|unsur\w*|puzzl\w*|" \
    r"perplex\w*|bewilder\w*|mystif\w*|lost\w*|" \
    r"unclear\w*|ambigu\w*|misunderstand\w*|misinterpret\w*|" \
    r"misread\w*|misjudg\w*|misperceiv\w*|misconceiv\w*|" \
    r"misconstru\w*|misidentif\w*|misapprehend\w*" \
r")\b"

# 4) question（普通问句：有问号或 wh-word）
pat_q = r"(\?)|\b(why|how|what|when|where|which)\b"

mask_fru  = text.str.contains(pat_fru,  regex=True)
mask_diff = text.str.contains(pat_diff, regex=True)
mask_conf = text.str.contains(pat_conf, regex=True)
mask_q    = text.str.contains(pat_q,    regex=True)

# 优先级赋值
filtered_1 = filtered.copy()  # 你的500条
filtered_1["is_question"] = mask_q.astype(int)
filtered_1["is_confusion"] = mask_conf.astype(int)
filtered_1["is_difficulty"] = mask_diff.astype(int)
filtered_1["is_frustration"] = mask_fru.astype(int)

#加一个“组合标签”列
def make_labels(row):
    labels = []
    if row["is_question"]: labels.append("QUESTION")
    if row["is_confusion"]: labels.append("CONFUSION")
    if row["is_difficulty"]: labels.append("DIFFICULTY")
    if row["is_frustration"]: labels.append("FRUSTRATION")
    return "|".join(labels) if labels else "NEUTRAL"

filtered_1["context_labels"] = filtered_1.apply(make_labels, axis=1)

filtered_1["context_labels"].value_counts()

/var/folders/c8/vcr8t_yn0wq2rqnv1b7cqrvr0000gn/T/ipykernel_9488/3438213134.py:38: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask_fru  = text.str.contains(pat_fru,  regex=True)
/var/folders/c8/vcr8t_yn0wq2rqnv1b7cqrvr0000gn/T/ipykernel_9488/3438213134.py:39: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask_diff = text.str.contains(pat_diff, regex=True)
/var/folders/c8/vcr8t_yn0wq2rqnv1b7cqrvr0000gn/T/ipykernel_9488/3438213134.py:40: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask_conf = text.str.contains(pat_conf, regex=True)
/var/folders/c8/vcr8t_yn0wq2rqnv1b7cqrvr0000gn/T/ipykernel_9488/3438213134.py:41: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask_q    = text.str.contains(pat_q,    regex=True)

context_labels
QUESTION                           383
QUESTION|DIFFICULTY                 42
NEUTRAL                             33
QUESTION|FRUSTRATION                18
QUESTION|CONFUSION                  11
DIFFICULTY                           6
QUESTION|DIFFICULTY|FRUSTRATION      5
QUESTION|CONFUSION|DIFFICULTY        3
FRUSTRATION                          2
Name: count, dtype: int64

In [40]:

filtered_1.head()

,id,context,teacher_response,is_question,is_confusion,is_difficulty,is_frustration,context_labels
0,train_2679,"Wether Almost. Whether WH - like when, where, what etc. Aha Ok, cool, you sound more confident with this material today, right? Yes Cool. I've got something for today, some bits of it will probably be very familiar, but some maybe new My birthday is __ March. We talked __ Skype. She's always ___ her phone. Could you insert some prepositions please? On march on Skype on her phone 43892.0 in March",Which month is your birthday?,1,0,0,0,QUESTION
3,train_2520,"At 6 And why are you only going to be studying for 11 years? It's our old programme and all children who went to school 2 years ago study for 12 years I see! It's a new rule then! Very interesting I went to school at 7 I see, me too! I think 7 is a good age to start school. Because you get 7 years of freeeedom :) Not really","and, of course, because children are much more mature at 7",1,0,0,0,QUESTION
6,train_2094,sorry I mean if you only say that exercise is the most importnatn thing So for example...in your opinion is diet as important as exercise or less important ? as important as exercise,ah ok! So if this is your 'thesis' then you should say that in the intro...hold on...,1,0,0,0,QUESTION
7,train_0566,"I see! It all makes sense, thank you very much! Also, really well done with all the writing today! But you still need to see gameplay Oh I will now, thank you. It'll be my homework :) Now, let's have a go at some sentences I copied from the chat. Could you insert the missing word? It's pretty warm with cat The cat? Yes, correct!",Ok and after that some funny fact about me,1,0,0,0,QUESTION
10,train_2241,"It is hot outside It's very hot here today, by English standards. +29 Wow I am okay, but I don’t know what to do What do you mean? Like Are you a bit confused about this lesson? or generally, you are not sure what to do with your time? Be a of the karantine, I can’t go somewhere So I am sitting at home And it is terrible","Ah, I'm with you. I have to stay at home, too!",1,1,0,0,QUESTION|CONFUSION

In [41]:
filtered_1 = filtered_1.reset_index(drop=True)
filtered_1.head()

,id,context,teacher_response,is_question,is_confusion,is_difficulty,is_frustration,context_labels
0,train_2679,"Wether Almost. Whether WH - like when, where, what etc. Aha Ok, cool, you sound more confident with this material today, right? Yes Cool. I've got something for today, some bits of it will probably be very familiar, but some maybe new My birthday is __ March. We talked __ Skype. She's always ___ her phone. Could you insert some prepositions please? On march on Skype on her phone 43892.0 in March",Which month is your birthday?,1,0,0,0,QUESTION
1,train_2520,"At 6 And why are you only going to be studying for 11 years? It's our old programme and all children who went to school 2 years ago study for 12 years I see! It's a new rule then! Very interesting I went to school at 7 I see, me too! I think 7 is a good age to start school. Because you get 7 years of freeeedom :) Not really","and, of course, because children are much more mature at 7",1,0,0,0,QUESTION
2,train_2094,sorry I mean if you only say that exercise is the most importnatn thing So for example...in your opinion is diet as important as exercise or less important ? as important as exercise,ah ok! So if this is your 'thesis' then you should say that in the intro...hold on...,1,0,0,0,QUESTION
3,train_0566,"I see! It all makes sense, thank you very much! Also, really well done with all the writing today! But you still need to see gameplay Oh I will now, thank you. It'll be my homework :) Now, let's have a go at some sentences I copied from the chat. Could you insert the missing word? It's pretty warm with cat The cat? Yes, correct!",Ok and after that some funny fact about me,1,0,0,0,QUESTION
4,train_2241,"It is hot outside It's very hot here today, by English standards. +29 Wow I am okay, but I don’t know what to do What do you mean? Like Are you a bit confused about this lesson? or generally, you are not sure what to do with your time? Be a of the karantine, I can’t go somewhere So I am sitting at home And it is terrible","Ah, I'm with you. I have to stay at home, too!",1,1,0,0,QUESTION|CONFUSION

In [42]:
filtered_1.shape

(503, 8)

In [43]:
filtered_1.to_csv("samples_after_1time_data_washing.csv")

## 2.Feature Engineering

In [44]:
df = pd.read_csv("samples_after_1time_data_washing.csv")
df.columns

Index(['Unnamed: 0', 'id', 'context', 'teacher_response', 'is_question',
       'is_confusion', 'is_difficulty', 'is_frustration', 'context_labels'],
      dtype='object')

In [45]:
dw2 = df[['id','context', 'teacher_response']].copy()
dw2.head()

,id,context,teacher_response
0,train_2679,"Wether Almost. Whether WH - like when, where, what etc. Aha Ok, cool, you sound more confident with this material today, right? Yes Cool. I've got something for today, some bits of it will probably be very familiar, but some maybe new My birthday is __ March. We talked __ Skype. She's always ___ her phone. Could you insert some prepositions please? On march on Skype on her phone 43892.0 in March",Which month is your birthday?
1,train_2520,"At 6 And why are you only going to be studying for 11 years? It's our old programme and all children who went to school 2 years ago study for 12 years I see! It's a new rule then! Very interesting I went to school at 7 I see, me too! I think 7 is a good age to start school. Because you get 7 years of freeeedom :) Not really","and, of course, because children are much more mature at 7"
2,train_2094,sorry I mean if you only say that exercise is the most importnatn thing So for example...in your opinion is diet as important as exercise or less important ? as important as exercise,ah ok! So if this is your 'thesis' then you should say that in the intro...hold on...
3,train_0566,"I see! It all makes sense, thank you very much! Also, really well done with all the writing today! But you still need to see gameplay Oh I will now, thank you. It'll be my homework :) Now, let's have a go at some sentences I copied from the chat. Could you insert the missing word? It's pretty warm with cat The cat? Yes, correct!",Ok and after that some funny fact about me
4,train_2241,"It is hot outside It's very hot here today, by English standards. +29 Wow I am okay, but I don’t know what to do What do you mean? Like Are you a bit confused about this lesson? or generally, you are not sure what to do with your time? Be a of the karantine, I can’t go somewhere So I am sitting at home And it is terrible","Ah, I'm with you. I have to stay at home, too!"

In [46]:
dw2[['STG_Empathy', 'STG_Encouragement','STG_Explanation', 'STG_Directive']] = 0
dw2.head()

,id,context,teacher_response,STG_Empathy,STG_Encouragement,STG_Explanation,STG_Directive
0,train_2679,"Wether Almost. Whether WH - like when, where, what etc. Aha Ok, cool, you sound more confident with this material today, right? Yes Cool. I've got something for today, some bits of it will probably be very familiar, but some maybe new My birthday is __ March. We talked __ Skype. She's always ___ her phone. Could you insert some prepositions please? On march on Skype on her phone 43892.0 in March",Which month is your birthday?,0,0,0,0
1,train_2520,"At 6 And why are you only going to be studying for 11 years? It's our old programme and all children who went to school 2 years ago study for 12 years I see! It's a new rule then! Very interesting I went to school at 7 I see, me too! I think 7 is a good age to start school. Because you get 7 years of freeeedom :) Not really","and, of course, because children are much more mature at 7",0,0,0,0
2,train_2094,sorry I mean if you only say that exercise is the most importnatn thing So for example...in your opinion is diet as important as exercise or less important ? as important as exercise,ah ok! So if this is your 'thesis' then you should say that in the intro...hold on...,0,0,0,0
3,train_0566,"I see! It all makes sense, thank you very much! Also, really well done with all the writing today! But you still need to see gameplay Oh I will now, thank you. It'll be my homework :) Now, let's have a go at some sentences I copied from the chat. Could you insert the missing word? It's pretty warm with cat The cat? Yes, correct!",Ok and after that some funny fact about me,0,0,0,0
4,train_2241,"It is hot outside It's very hot here today, by English standards. +29 Wow I am okay, but I don’t know what to do What do you mean? Like Are you a bit confused about this lesson? or generally, you are not sure what to do with your time? Be a of the karantine, I can’t go somewhere So I am sitting at home And it is terrible","Ah, I'm with you. I have to stay at home, too!",0,0,0,0

In [47]:
dw2.to_csv("teacher_strategy_annotation_v1.csv")

## 3.Pilot Annotation

In [48]:
df = pd.read_csv("samples_after_1time_data_washing.csv")
dw3 = df[['id', 'context', 'teacher_response']].copy()
dw3.shape

(503, 3)

In [49]:
pilot_dw3 = dw3.sample(20, random_state=42).reset_index(drop=True)
pilot_dw3[['support_score']] = 0 
pilot_dw3.head()

,id,context,teacher_response,support_score
0,train_1357,"Thank you. I understood. I'll think again about my explanation before and improve it for next time with examples! Thank you. Is there any rule?? Sorry, 'rules'","One last task on this topic <STUDENT>: could you tell me a time you were: suspicious/curious By the way, sorry no rule! Adjectives + prepositions is a bit unpredictable I'm afraid...",0
1,train_2361,"Have you followed any of the news in English? Yes, I follow BBC News on facebook so everyday I read something, at least the headlines Finally your president in not in intensive care whatever haha I don't know the words OK right - very conscientious of you - so yeah , you'll have picked up all the phrases we use....it's all good vocabulary no , intensive care = perfectly correct",yes he's out now...so i guess he'll recover,0
2,train_1648,"You stroked a white dog? You opened a packet of crisps? Hint was about crisps Hint : money Ok, did you count every crips in the packet because you were bored? Did you sell crisps to earn some pocket money? No, but it is funny guess I give up! I ... some crisps today Sure? Did you eat them? Not Did you spill them on the flour? floor, sorrry sorry I didn’t open them!","Ah, you have some willpower!",0
3,train_0942,"Sounds cool, thanks for that! It's probably aimed at teenagers though, not young kids, right? It's teen but you need to see gameplay If you want , I can send one I'm sure I can find it, thank you! It's reassuring that there is no blood So what's the fun fact about you? :) Have you ever played star wars lego?",Yes! We like it a lot,0
4,train_0431,"4 or 5 if you like Do you mean like 'curiosity?' Exactly impression, relief, confusion,excitement Thanks - could you choose two of those and give me an example? The film gave me impression. Thanks <STUDENT> - do you mean : I was impressed by the film? Yes. Is that correct?",Sorry I mean <STUDENT> - unfortunate error!,0

In [50]:

pilot_dw3.to_csv("pilot_annotation_20_samples.csv")

## 4.Final Annotation Dataset

In [51]:
df = pd.read_csv("samples_after_1time_data_washing.csv")
dw4 = df[['id', 'context', 'teacher_response']].copy()
dw4.shape

(503, 3)

In [52]:
dw4[['support_score']] = 0 
dw4.head()

,id,context,teacher_response,support_score
0,train_2679,"Wether Almost. Whether WH - like when, where, what etc. Aha Ok, cool, you sound more confident with this material today, right? Yes Cool. I've got something for today, some bits of it will probably be very familiar, but some maybe new My birthday is __ March. We talked __ Skype. She's always ___ her phone. Could you insert some prepositions please? On march on Skype on her phone 43892.0 in March",Which month is your birthday?,0
1,train_2520,"At 6 And why are you only going to be studying for 11 years? It's our old programme and all children who went to school 2 years ago study for 12 years I see! It's a new rule then! Very interesting I went to school at 7 I see, me too! I think 7 is a good age to start school. Because you get 7 years of freeeedom :) Not really","and, of course, because children are much more mature at 7",0
2,train_2094,sorry I mean if you only say that exercise is the most importnatn thing So for example...in your opinion is diet as important as exercise or less important ? as important as exercise,ah ok! So if this is your 'thesis' then you should say that in the intro...hold on...,0
3,train_0566,"I see! It all makes sense, thank you very much! Also, really well done with all the writing today! But you still need to see gameplay Oh I will now, thank you. It'll be my homework :) Now, let's have a go at some sentences I copied from the chat. Could you insert the missing word? It's pretty warm with cat The cat? Yes, correct!",Ok and after that some funny fact about me,0
4,train_2241,"It is hot outside It's very hot here today, by English standards. +29 Wow I am okay, but I don’t know what to do What do you mean? Like Are you a bit confused about this lesson? or generally, you are not sure what to do with your time? Be a of the karantine, I can’t go somewhere So I am sitting at home And it is terrible","Ah, I'm with you. I have to stay at home, too!",0

In [56]:
dw4_1st_part = dw4[: 251].copy()
dw4_2nd_part = dw4[251 :].copy()
dw4.to_csv("annot_data_full.csv", index=True)
dw4_1st_part.to_csv("annot_data_part1.csv", index=True)
dw4_2nd_part.to_csv("annot_data_part2.csv", index=True)